### PR TITLE
Revert: polykinds branch

### PR DESCRIPTION
**Pull request by qnikst**

### CODE REVIEW

**Comment by facundominguez** [comment]
LGTM. Please edit the comment to something like:

    Revert 36092f6: Implement encoding for higher-kinded variables.
    
    The approach relied on defining a Typeable instance for Any. In ghc 7.10,
    Any has been redefined and is no longer a datatype, so a Typeable
    instance for it is no longer possible.

**Comment by qnikst** [comment]
Updated

**Comment by facundominguez** [comment]
Merged to master as 1809a7f.

**Comment by qnikst** [comment]
Could you make a version bump and upload library on a hackage?

**Pull request closed without merging**
